package com.thizthizzydizzy.aoc2021;
public class Main{
    public static void main(String[] args){
//        System.out.println("Day 1");
//        new Day1().run();
//        System.out.println("Day 2");
//        new Day2().run();
//        System.out.println("Day 3");
//        new Day3().run();
//        System.out.println("Day 4");
//        new Day4().run();
//        System.out.println("Day 5");
//        new Day5().run();
//        System.out.println("Day 6");
//        new Day6().run();
//        System.out.println("Day 7");
//        new Day7().run();
//        System.out.println("Day 8");
//        new Day8().run();
//        System.out.println("Day 9");
//        new Day9().run();
//        System.out.println("Day 10");
//        new Day10().run();
//        System.out.println("Day 11");
//        new Day11().run();
//        System.out.println("Day 12");
//        new Day12().run();
//        System.out.println("Day 13");
//        new Day13().run();
//        System.out.println("Day 14");
//        new Day14().run();
//        System.out.println("Day 15");
//        new Day15().run();
//        System.out.println("Day 16");
//        new Day16().run();
//        System.out.println("Day 17");
//        new Day17().run();
//        System.out.println("Day 18");
//        new Day18().run();
//        System.out.println("Day 19");
//        new Day19().run();
//        System.out.println("Day 20");
//        new Day20().run();
//        System.out.println("Day 21");
//        new Day21().run();
//        System.out.println("Day 22");
//        new Day22().run();
//        System.out.println("Day 23");
//        new Day23().run();
        System.out.println("Day 24");
        new Day24().run();
    }
}